#!/usr/bin/env python
#-*- coding:utf-8 -*-
#重心を含めたヒートマップを画像として書き出す

import glob
import os, commands
import os.path
from tqdm import tqdm
from scipy import stats
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
import sys
import seaborn as sns
import cv2
commands.getoutput("find . -name '.DS_Store' -type f -ls -delete")
args = sys.argv


class COG_FigClass:

    """補正後の個人データを画像出力"""

    def plot_Heatmap(self,Motion,COGdata,figSavePath):
        line,column,frame = Motion.shape
        mask = np.zeros([line,column])

        for lines in range(line):
            for columns in range(column):
                for frames in range(frame):
                    index = np.where(Motion[:,:,frames] > 0)
                    mask[index[0],index[1]] = 1

                    fig, ax = plt.subplots(figsize=(25, 20))
                    sns.heatmap(Motion[:,:,frames], mask=mask[:,:],vmin=0, cmap='viridis',linecolor='black',linewidths=0.1)
                    # ax.set_xticks(np.arange(Motion[:,:,0].shape[0]) + 0.5, minor=False)
                    # ax.set_yticks(np.arange(Motion[:,:,0].shape[1]) + 0.5, minor=False)
                    # ax.xaxis.tick_top()
                    # ax.set_xticklabels(np.arange(60), minor=False)
                    # ax.set_yticklabels(np.arange(60), minor=False)
                    plt.scatter(COGdata[frames,1],COGdata[frames,0], s=2500,c="yellow", marker="*",linewidths="2",edgecolors="orange")
                    plt.scatter(COGdata[frames,4],COGdata[frames,3], s=2500,c="red", marker="*",linewidths="2",edgecolors="orange")
                    plt.scatter(COGdata[frames,7],COGdata[frames,6], s=2500,c="green", marker="*",linewidths="2",edgecolors="orange")
                    plt.savefig(figSavePath+"/"+str(frames)+".png")
                    plt.close()

if __name__ == '__main__':
    COGFCla= COG_FigClass()

    #Row_Motion
    npyPath_list = glob.glob('../npyGen/NPY/Motion_Data/*.npy')#'../npyGen/NPY/Motion_Data/Dentifrice.npy',...
    for npyPath in tqdm(npyPath_list):#'../npyGen/NPY/Motion_Data/Dentifrice.npy',...

        MotionSavePath = npyPath.replace('../npyGen/NPY/Motion_Data/','./Row_Motion/')#'./Row_Motion/Dentifrice.npy'...
        MotionSavePath = MotionSavePath.replace('.npy','/Heatmap')#'./Row_Motion_COG/Dentifrice/Heatmap'...
        COGPath = npyPath.replace('../npyGen/NPY/Motion_Data/','./Row_Motion_COG/')#'./Row_Motion_COG/Dentifrice.npy'...
        COGPath = COGPath.replace('.npy','_COG.npy')#'./Row_Motion_COG/Dentifrice_COG.npy'...
        if os.path.isdir(MotionSavePath) == False:#なければ保存用のディレクトリ作成
            os.mkdir(MotionSavePath)#'./Row_Motion_COG/Dentifrice/Heatmap'...

        Motiondata = np.load(npyPath)
        COGdata = np.load(COGPath)
        COGFCla.plot_Heatmap(Motiondata,COGdata,MotionSavePath)



    # Cabed_Motion
    MotionPath_list = glob.glob('./Cabed_Motion/*')#'./Cabed_Motion/Dentifrice'...
    for MotionPath in tqdm(MotionPath_list):#'./Cabed_Motion/Dentifrice'...
        npyPath_list = glob.glob(MotionPath+'/*.npy')#'Cabed_Motion/Dentifrice/cabed_all.npy'...
        for npyPath in npyPath_list:#'Cabed_Motion/Dentifrice/cabed_all.npy'...
            figSavePath = npyPath.replace('cabed_','')#'Cabed_Motion/Dentifrice/all.npy'...
            figSavePath = figSavePath.replace('.npy','/Heatmap')#'Cabed_Motion/Dentifrice/all/Heatmap'...
            COGPath = npyPath.replace('Cabed_Motion/','./Cabed_Motion_COG/')#'./Cabed_Motion_COG/Dentifrice/cabed_all.npy'...
            COGPath = COGPath.replace('.npy','_COG.npy')#'./Row_Motion_COG/Dentifrice/cabed_all_COG.npy'...
            if os.path.isdir(figSavePath) == False:#なければ保存用のディレクトリ作成
                    os.mkdir(figSavePath)#'./Row_Motion_COG/Dentifrice/Heatmap'...
            Motiondata = np.load(npyPath)
            COGdata = np.load(COGPath)
            COGFCla.plot_Heatmap(Motiondata,COGdata,figSavePath)




    #Cabed_Motion//Dentifrice/ED44
    MotionPath_list = glob.glob('./Cabed_Motion/*')#'./Cabed_Motion/Dentifrice'...
    for MotionPath in tqdm(MotionPath_list):#'./Cabed_Motion/Dentifrice'...
        EDPath_list = glob.glob(MotionPath+'/ED*')#'Cabed_Motion/Dentifrice/ED44'...
        for EDPath in EDPath_list:#'Cabed_Motion/Dentifrice/ED44'...
            npyPath_list = glob.glob(EDPath+'/*.npy')#'Cabed_Motion/Dentifrice/ED44/cabed_all.npy'...
            for npyPath in npyPath_list:
                figSavePath = npyPath.replace('cabed_','')#'Cabed_Motion/Dentifrice/ED44/all.npy'...
                figSavePath = figSavePath.replace('.npy','/Heatmap')#'Cabed_Motion/Dentifrice/ED44/all/Heatmap'...
                COGPath = npyPath.replace('Cabed_Motion/','./Cabed_Motion_COG/')#'./Cabed_Motion_COG/Dentifrice/ED44/cabed_all.npy'...
                COGPath = COGPath.replace('.npy','_COG.npy')#'./Row_Motion_COG/Dentifrice/ED44/cabed_all_COG.npy'...
                if os.path.isdir(figSavePath) == False:#なければ保存用のディレクトリ作成
                        os.mkdir(figSavePath)#'./Row_Motion_COG/Dentifrice/ED44/Heatmap'...
                Motiondata = np.load(npyPath)
                COGdata = np.load(COGPath)
                COGFCla.plot_Heatmap(Motiondata,COGdata,figSavePath)



    # DirPath_list = glob.glob('./ED*_Person')
    #
    # for DirPath in tqdm(DirPath_list):
    #
    #         NamePath_list = glob.glob(DirPath+'/*')#'ED44Cabed_Person/jyu'...
    #
    #         for NamePath in NamePath_list:
    #
    #             npyPath_list = glob.glob(NamePath+'/*.npy')
    #
    #             for npyPath in npyPath_list:#'ED44Cabed_Person/jyu/cabed_all_1_ED.npy'...
    #                 figSavePath = npyPath.replace('Person','COG')#'ED44Cabed_COG/jyu/cabed_all_1_ED.npy'...
    #                 COGPath = figSavePath.replace('_ED.npy','_ED_COG.npy')#'ED44Cabed_COG/jyu/cabed_all_1_ED_COG.npy',...
    #                 figSavePath = figSavePath.replace('cabed_all_','')#'ED44Cabed_COG/jyu/1_ED.npy'...
    #                 figSavePath = figSavePath.replace('cabed_rep_','')#'ED44Cabed_COG/jyu/1_ED.npy'...
    #                 figSavePath = figSavePath.replace('_ED.npy','')#'ED44Cabed_COG/jyu/1',...
    #                 all_figSavePath = figSavePath+'/all/'#'./NewCabed_Person/jyu/1/all/',...
    #                 rep_figSavePath = figSavePath+'/rep/'#'./NewCabed_Person/jyu/1/rep/',...
    #
    #                 person = np.load(npyPath)
    #                 COGdata = np.load(COGPath)
    #
    #                 if 'all' in npyPath:
    #                     COGFCla.plot_COG(person,COGdata,all_figSavePath)
    #                 elif 'rep' in npyPath:
    #                     COGFCla.plot_COG(person,COGdata,rep_figSavePath)

    # DirPath_list = glob.glob('./ED*_Dent')
    #
    # for DirPath in tqdm(DirPath_list):
    #
    #     npyPath_list = glob.glob(DirPath+'/*.npy')#'ED44Cabed_Dent/1956_cabed_all_ED.py'...
    #
    #     for npyPath in npyPath_list:#'ED44Cabed_Dent/jyu/cabed_all_1_ED.npy'...
    #         figSavePath = npyPath.replace('Dent','Dent_COG')#'ED44Cabed_Dent_COG/1956_cabed_all_ED.py'...
    #         COGPath = figSavePath.replace('_ED.npy','_ED_COG.npy')#'ED44Cabed_COG/1956_cabed_all_ED_COG.py'...
    #         figSavePath = figSavePath.replace('cabed_all_','')#'ED44Cabed_COG/1956_ED.py'...
    #         figSavePath = figSavePath.replace('cabed_rep_','')#'ED44Cabed_COG/1956_ED.py'...
    #         figSavePath = figSavePath.replace('1956_ED.npy','')#'ED44Cabed_COG/1956',...
    #         if os.path.isdir(figSavePath) == False:#なければ保存用のディレクトリ作成
    #             os.mkdir(figSavePath)#'./NewCabed_Dent/1964/all/'...
    #         all_figSavePath = figSavePath+'all/'#'./NewCabed_Dent/1956/all/',...
    #         rep_figSavePath = figSavePath+'rep/'#'./NewCabed_Dent/1956/rep/',...
    #         if os.path.isdir(all_figSavePath) == False:#なければ保存用のディレクトリ作成
    #             os.mkdir(all_figSavePath)#'./NewCabed_Dent/1964/all/'...
    #         if os.path.isdir(rep_figSavePath) == False:#なければ保存用のディレクトリ作成
    #             os.mkdir(rep_figSavePath)#'./NewCabed_Dent/1964/rep/'...
    #
    #         Dentdata = np.load(npyPath)
    #         COGdata = np.load(COGPath)
    #
    #
    #         if 'all' in npyPath:
    #             maskPath = all_figSavePath.replace('Dent_COG','Dent')#'ED44Cabed_Dent_COG/1956_cabed_all_ED.py'...
    #             mask = np.load(maskPath+'mask.npy')
    #             COGFCla.plot_COG(Dentdata,COGdata,mask,all_figSavePath)
    #         elif 'rep' in npyPath:
    #             maskPath = rep_figSavePath.replace('Dent_COG','Dent')#'ED44Cabed_Dent_COG/1956_cabed_all_ED.py'...
    #             mask = np.load(maskPath+'mask.npy')
    #             COGFCla.plot_COG(Dentdata,COGdata,mask,rep_figSavePath)

    # npyPath_list = glob.glob('../npyGen/NPY/Dentifrice_Cleaned/*.npy')#'../npyGen/NPY/Dentifrice_Cleaned/1964.npy',...
    #
    # for npyPath in npyPath_list:#'../npyGen/NPY/Dentifrice_Cleaned/1964.npy',...
    #     figSavePath = npyPath.replace('../npyGen/NPY/Dentifrice_Cleaned','./Row_Dent')#'./Row_Dent/1956.py',...
    #     COGPath = figSavePath.replace('./Row_Dent','./Row_Dent_COG')#'./Row_Dent_COG/1956.py'...
    #     COGPath = COGPath.replace('.npy','_COG.npy')#'./Row_Dent_Raw/1956_COG.py'...
    #     figSavePath = figSavePath.replace('1956.npy','')#'./Row_Dent/',...
    #
    #     Dentdata = np.load(npyPath)
    #     COGdata = np.load(COGPath)
    #     mask = np.load(figSavePath+'mask.npy')
    #     COGFCla.plot_COG(Dentdata,COGdata,mask,figSavePath)
